version: '3'
services:
  backend:
    container_name: backend
    # image: wachayathorn/smarthome:latest
    build: .
    image: smarthome_backend
    restart: always
    ports:
      - 3030:3000
    environment:
      - TYPEORM_TYPE=mysql
      - TYPEORM_HOST=35.185.190.1
      - TYPEORM_PORT=31593
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=P@ssw0rd
      - TYPEORM_DATABASE=SMARTHOME
      - REDIS_SERVER=redis://35.185.190.1:30884
      - HPPT_PORT=3000
      - TOKEN_EXPIRE=1d
      - JWT_SECRET=SMARTHOME
      - SALT_ROUNDS=9
    # depends_on: 
    #   - mariadb
    #   - redis
  # mysql:
  #   container_name: mariadb
  #   image: mariadb:10.6.0
  #   restart: always
  #   ports:
  #     - 43306:3306
  #   environment:
  #     - MARIADB_ROOT_PASSWORD: P@ssw0rd
  #     - MARIADB_DATABASE: SMARTHOME
  # redis:
  #     container_name: redis
  #     image: redis:alpine
  #     restart: always
  #     ports:
  #       - 6380:6379