version: '3'
services:
  backend:
    container_name: backend
    image: wachayathorn/smarthome:latest
    restart: always
    ports:
      - 3030:3000
    environment:
      - TYPEORM_TYPE=mysql
      - TYPEORM_HOST=3.142.219.106
      - TYPEORM_PORT=43306
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=P@ssw0rd
      - TYPEORM_DATABASE=Smart-Home
      - REDIS_SERVER=redis://3.142.219.106:6380
      - HPPT_PORT=3000
  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - 43306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD: P@ssw0rd
  #   redis:
  #     container_name: redis
  #     image: redis:alpine
  #     restart: always
  #     ports:
  #       - 6380:6379